name: SDK Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v -args ${{ secrets.PAGECALL_API_KEY }} ${{ secrets.PAGECALL_LAYOUT_ID }}
        working-directory: ./pagecall
